export const Cat = [
  {
    id: 1,
    name: "LG Washing machine",
    price: "Rs:800",
    image: "/assets/washing_machine.png",
    cat_id: 4,
    subcat: 4,
    offer: "12%",
  },
  {
    id: 2,
    name: "PlayStation Joystick EC234",
    price: "Rs:800",
    image: "/assets/Joystick.png",
    cat_id: 11,
    subcat: 180,
    offer: "19%",
  },
  {
    id: 3,
    name: "Tv",
    image: "/assets/tv.png",
    price: "Rs:800",
    cat_id: 2,
    subcat: 60,
    offer: "4%",
  },
  {
    id: 4,
    name: "Watch",
    price: "Rs:800",
    image: "/assets/watch1.png",
    cat_id: 6,
    subcat: 40,
    offer: "3%",
  },
  {
    id: 5,
    name: "Headphone",
    price: "Rs:800",
    cat_id: 9,
    subcat: 50,
    image: "/assets/headphone1.png",
    offer: "8%",
  },
  {
    id: 6,
    name: "Iphone",
    price: "Rs:114800",
    cat_id: 1,
    subcat: 3,
    image: "/assets/iphone2.png",
    offer: "2%",
  },
  {
    id: 7,
    name: "Smart Watches",
    price: "Rs:1800",
    cat_id: 4,
    subcat: 40,
    image: "/assets/watch2.png",
    offer: "1%",
  },
  {
    id: 8,
    name: "Blutooth Speaker",
    price: "Rs:1200",
    cat_id: 8,
    subcat: 30,
    image: "/assets/blutooth_speaker.png",
    offer: "1%",
  },

  {
    id: 9,
    name: "Samsung Washing machine",
    price: "Rs:800",
    image: "/assets/washing_machine.png",
    cat_id: 4,
    subcat: 5,
    offer: "12%",
  },
  {
    id: 10,
    name: "Samsung",
    price: "Rs:114800",
    cat_id: 1,
    subcat: 2,
    image: "/assets/sam.png",
    offer: "2%",
  },
  {
    id: 11,
    name: "redmi",
    price: "Rs:114800",
    cat_id: 1,
    subcat: 1,
    image: "/assets/sam.png",
    offer: "2%",
  },
  {
    id: 12,
    name: "Refridgerator",
    price: "Rs:114800",
    cat_id: 5,
    subcat: 70,
    image: "/assets/fridge.png",
    offer: "2%",
  },
];
