import Head from "next/head";
import Swiper from "../components/swiper";
import Delivery from "@/components/delivery";
import Categories from "@/components/categories";
import Bestdeals from "@/components/bestdeals";
import Topproducts from "@/components/topproducts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Swiper />
        <Delivery />
        <Categories />
        <Bestdeals/>
        <Topproducts/>
      </main>
    </>
  );
}
